application: carles
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /scripts
  static_dir: scripts

- url: /styles
  static_dir: styles

- url: /img
  static_dir: img
  
- url: /.*
  script: carles.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

