application: webstudentlife
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /scripts
  static_dir: scripts
- url: /es/scripts
  static_dir: scripts  
- url: /en/scripts
  static_dir: scripts
- url: /gestio/scripts
  static_dir: scripts
  
- url: /styles
  static_dir: styles
- url: /es/styles
  static_dir: styles  
- url: /en/styles
  static_dir: styles

- url: /img
  static_dir: img
- url: /es/img
  static_dir: img  
- url: /en/img
  static_dir: img
  
- url: /fitxers
  static_dir: fitxers
  
- url: /gestio
  script: carles.app
  login: admin

- url: /.*
  script: carles.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

